---
- name: Nutnaix Cluster Information
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - ./login.yml

  tasks:
  - name: Get Cluster Info
    uri:
      url: "https://{{ prism_address }}:9440/api/nutanix/v2.0/clusters/"
      method: GET
      user: "{{ prism_username }}"
      password: "{{ prism_password }}"
      body_format: json
      force_basic_auth: yes
      validate_certs: no
      status_code: 200
    register: nutanix_clusters

  - name: Output Cluster Info
    debug:
      var: nutanix_clusters.json.entities

